export const adminSettingsTranslations = {
  'pt-PT': { admin:{ settings:{
    navigation:{ label:'Configurações administrativas', tabs:{ profiles:'Perfis', adminRoles:'Roles de Admin', genders:'Géneros', orientations:'Orientações', intentions:'Intenções', limits:'Limites', privateInterests:'Interesses privados', locations:'Localidades', subscriptions:'Subscrições', email:'Email', guide:'Guia', events:'Eventos', circles:'Circles', recommendations:'Recomendações', referrals:'Afiliados' } },
    email:{ title:'Email e acesso de emergência', smtpTitle:'Configuração SMTP', test:'Testar', diagnosticError:'Não foi possível obter o diagnóstico.', status:{ ok:'SMTP ligado', misconfigured:'Não configurado', error:'Erro de ligação' }, missing:'Variáveis em falta no Railway', hints:'Sugestões', currentValues:'Valores atuais', undefined:'(não definido)', testEmailTitle:'Enviar email de teste', destination:'email@destino.com', send:'Enviar', sent:'Email enviado para {email}', sendError:'Não foi possível enviar o email.', otpTitle:'Login de emergência (OTP)', otpDescription:'Gera um link de login único, válido durante 15 minutos, sem depender do envio de email.', userEmail:'Email do utilizador', generate:'Gerar', otpError:'Não foi possível gerar o OTP.', otpLink:'Link de login (uma utilização · 15 min)', copy:'Copiar link' },
    referrals:{ title:'Regra de afiliados', description:'Regra de recompensa por convites, editável sem alterar código. Quando um utilizador atinge o número configurado de convidados subscritos, recebe automaticamente os meses de prémio.', required:'Convites subscritos necessários', months:'Meses de prémio oferecidos', loadError:'Não foi possível carregar a regra.', saveError:'Não foi possível guardar a regra.', updated:'Regra atualizada.', saving:'A guardar…', save:'Guardar regra', current:'Regra atual: cada {required} convidados que subscrevam atribuem {months} meses de prémio.' },
  } } },
  en: { admin:{ settings:{
    navigation:{ label:'Administrative settings', tabs:{ profiles:'Profiles', adminRoles:'Admin roles', genders:'Genders', orientations:'Orientations', intentions:'Intentions', limits:'Limits', privateInterests:'Private interests', locations:'Locations', subscriptions:'Subscriptions', email:'Email', guide:'Guide', events:'Events', circles:'Circles', recommendations:'Recommendations', referrals:'Referrals' } },
    email:{ title:'Email and emergency access', smtpTitle:'SMTP configuration', test:'Test', diagnosticError:'The diagnostic could not be retrieved.', status:{ ok:'SMTP connected', misconfigured:'Not configured', error:'Connection error' }, missing:'Missing Railway variables', hints:'Suggestions', currentValues:'Current values', undefined:'(undefined)', testEmailTitle:'Send test email', destination:'destination@example.com', send:'Send', sent:'Email sent to {email}', sendError:'The email could not be sent.', otpTitle:'Emergency login (OTP)', otpDescription:'Generates a single-use login link valid for 15 minutes without relying on email delivery.', userEmail:'User email', generate:'Generate', otpError:'The OTP could not be generated.', otpLink:'Login link (one use · 15 min)', copy:'Copy link' },
    referrals:{ title:'Referral rule', description:'Referral reward rule editable without changing code. When a user reaches the configured number of subscribed invitees, the reward months are granted automatically.', required:'Required subscribed invitations', months:'Reward months', loadError:'The rule could not be loaded.', saveError:'The rule could not be saved.', updated:'Rule updated.', saving:'Saving…', save:'Save rule', current:'Current rule: every {required} subscribed invitees grant {months} reward months.' },
  } } },
  fr: { admin:{ settings:{
    navigation:{ label:'Paramètres administratifs', tabs:{ profiles:'Profils', adminRoles:'Rôles administratifs', genders:'Genres', orientations:'Orientations', intentions:'Intentions', limits:'Limites', privateInterests:'Intérêts privés', locations:'Localités', subscriptions:'Abonnements', email:'E-mail', guide:'Guide', events:'Événements', circles:'Cercles', recommendations:'Recommandations', referrals:'Parrainages' } },
    email:{ title:'E-mail et accès d’urgence', smtpTitle:'Configuration SMTP', test:'Tester', diagnosticError:'Le diagnostic n’a pas pu être obtenu.', status:{ ok:'SMTP connecté', misconfigured:'Non configuré', error:'Erreur de connexion' }, missing:'Variables Railway manquantes', hints:'Suggestions', currentValues:'Valeurs actuelles', undefined:'(non défini)', testEmailTitle:'Envoyer un e-mail de test', destination:'destination@exemple.com', send:'Envoyer', sent:'E-mail envoyé à {email}', sendError:'L’e-mail n’a pas pu être envoyé.', otpTitle:'Connexion d’urgence (OTP)', otpDescription:'Génère un lien de connexion à usage unique valable 15 minutes sans dépendre de l’envoi d’e-mail.', userEmail:'E-mail de l’utilisateur', generate:'Générer', otpError:'L’OTP n’a pas pu être généré.', otpLink:'Lien de connexion (un usage · 15 min)', copy:'Copier le lien' },
    referrals:{ title:'Règle de parrainage', description:'Règle de récompense modifiable sans changer le code. Lorsque le nombre configuré d’invités abonnés est atteint, les mois de récompense sont accordés automatiquement.', required:'Invitations abonnées nécessaires', months:'Mois de récompense', loadError:'La règle n’a pas pu être chargée.', saveError:'La règle n’a pas pu être enregistrée.', updated:'Règle mise à jour.', saving:'Enregistrement…', save:'Enregistrer la règle', current:'Règle actuelle : chaque groupe de {required} invités abonnés accorde {months} mois de récompense.' },
  } } },
}
