export const adminCatalogSettingsTranslations = {
  'pt-PT': { admin:{ settings:{
    catalogs:{ genders:'Géneros', gender:'género', orientations:'Orientações', orientation:'orientação', intentions:'Intenções', intention:'intenção', privateInterests:'Interesses privados', privateInterest:'interesse privado' },
    catalog:{ loadError:'Não foi possível carregar {catalog}.', required:'Nome e slug são obrigatórios.', saveError:'Não foi possível guardar.', deleteError:'Não foi possível apagar.', inUseConfirm:'Esta opção está em uso por {count} perfil(is). Desativar em vez de apagar?', deleteConfirm:'Apagar esta opção?', newTitle:'Nova opção de {catalog}', editTitle:'Editar opção', save:'Guardar', name:'Nome', slug:'Slug', description:'Descrição', category:'Categoria', active:'Ativa', count:'{total} opções · {active} ativas', new:'Nova', empty:'Não existem opções de {catalog} configuradas.', inactive:'inativa', usage:'usada por {count} perfil(is)', edit:'Editar', deactivate:'Desativar', activate:'Ativar', delete:'Apagar' },
  } } },
  en: { admin:{ settings:{
    catalogs:{ genders:'Genders', gender:'gender', orientations:'Orientations', orientation:'orientation', intentions:'Intentions', intention:'intention', privateInterests:'Private interests', privateInterest:'private interest' },
    catalog:{ loadError:'{catalog} could not be loaded.', required:'Name and slug are required.', saveError:'The option could not be saved.', deleteError:'The option could not be deleted.', inUseConfirm:'This option is used by {count} profile(s). Deactivate it instead of deleting?', deleteConfirm:'Delete this option?', newTitle:'New {catalog} option', editTitle:'Edit option', save:'Save', name:'Name', slug:'Slug', description:'Description', category:'Category', active:'Active', count:'{total} options · {active} active', new:'New', empty:'No {catalog} options are configured.', inactive:'inactive', usage:'used by {count} profile(s)', edit:'Edit', deactivate:'Deactivate', activate:'Activate', delete:'Delete' },
  } } },
  fr: { admin:{ settings:{
    catalogs:{ genders:'Genres', gender:'genre', orientations:'Orientations', orientation:'orientation', intentions:'Intentions', intention:'intention', privateInterests:'Intérêts privés', privateInterest:'intérêt privé' },
    catalog:{ loadError:'Impossible de charger {catalog}.', required:'Le nom et le slug sont obligatoires.', saveError:'L’option n’a pas pu être enregistrée.', deleteError:'L’option n’a pas pu être supprimée.', inUseConfirm:'Cette option est utilisée par {count} profil(s). La désactiver au lieu de la supprimer ?', deleteConfirm:'Supprimer cette option ?', newTitle:'Nouvelle option de {catalog}', editTitle:'Modifier l’option', save:'Enregistrer', name:'Nom', slug:'Slug', description:'Description', category:'Catégorie', active:'Active', count:'{total} options · {active} actives', new:'Nouvelle', empty:'Aucune option de {catalog} n’est configurée.', inactive:'inactive', usage:'utilisée par {count} profil(s)', edit:'Modifier', deactivate:'Désactiver', activate:'Activer', delete:'Supprimer' },
  } } },
}
