export const adminUserPanelsTranslations = {
  'pt-PT': { admin: {
    userProfile:{ title:'Perfil público', empty:'Sem perfil criado.', save:'Guardar', saveTitle:'Guardar perfil', updated:'Perfil atualizado.', actionError:'Não foi possível atualizar o perfil.', readOnly:'Campos só de leitura', intentions:'Intenções', yes:'Sim', no:'Não', photoCount:'{count} fotos', status:{ DRAFT:'Rascunho', PENDING_REVIEW:'Pendente de revisão', APPROVED:'Aprovado', REJECTED:'Rejeitado', HIDDEN:'Oculto', SUSPENDED:'Suspenso' }, fields:{ status:'Estado', type:'Tipo', displayName:'Nome visível', bio:'Bio', city:'Cidade', relationshipStatus:'Estado relacional', discretion:'Discrição', gender:'Género', orientation:'Orientação', country:'País', photos:'Fotos', verified:'Verificado', createdAt:'Criado em' } },
    userSubscription:{ title:'Subscrição e informação financeira', empty:'Sem subscrição.', current:'Subscrição atual', plan:'Plano', status:'Estado', provider:'Fornecedor', startedAt:'Início da subscrição', periodStart:'Período atual desde', periodEnd:'Período atual até', cancelAtEnd:'Cancela no fim do período', cancelledAt:'Cancelada em', currentPeriod:'Período atual', amountPaid:'Valor pago neste período', lifetime:'Histórico total', totalPaid:'Total pago desde a criação da conta', successfulPayments:'Pagamentos com sucesso', lastPayment:'Último pagamento', failedPayments:'Pagamentos falhados nos últimos 90 dias', noLocalHistory:'Dados históricos não disponíveis localmente.', testAccountNote:'Conta de teste — não gera eventos reais do Stripe.', yes:'Sim', no:'Não' },
  }},
  en: { admin: {
    userProfile:{ title:'Public profile', empty:'No profile has been created.', save:'Save', saveTitle:'Save profile', updated:'Profile updated.', actionError:'The profile could not be updated.', readOnly:'Read-only fields', intentions:'Intentions', yes:'Yes', no:'No', photoCount:'{count} photos', status:{ DRAFT:'Draft', PENDING_REVIEW:'Pending review', APPROVED:'Approved', REJECTED:'Rejected', HIDDEN:'Hidden', SUSPENDED:'Suspended' }, fields:{ status:'Status', type:'Type', displayName:'Display name', bio:'Bio', city:'City', relationshipStatus:'Relationship status', discretion:'Discretion', gender:'Gender', orientation:'Orientation', country:'Country', photos:'Photos', verified:'Verified', createdAt:'Created on' } },
    userSubscription:{ title:'Subscription and financial information', empty:'No subscription.', current:'Current subscription', plan:'Plan', status:'Status', provider:'Provider', startedAt:'Subscription started', periodStart:'Current period from', periodEnd:'Current period until', cancelAtEnd:'Cancels at period end', cancelledAt:'Cancelled on', currentPeriod:'Current period', amountPaid:'Amount paid in this period', lifetime:'Lifetime history', totalPaid:'Total paid since account creation', successfulPayments:'Successful payments', lastPayment:'Last payment', failedPayments:'Failed payments in the last 90 days', noLocalHistory:'Historical data is not available locally.', testAccountNote:'Test account — does not generate real Stripe events.', yes:'Yes', no:'No' },
  }},
  fr: { admin: {
    userProfile:{ title:'Profil public', empty:'Aucun profil créé.', save:'Enregistrer', saveTitle:'Enregistrer le profil', updated:'Profil mis à jour.', actionError:'Le profil n’a pas pu être mis à jour.', readOnly:'Champs en lecture seule', intentions:'Intentions', yes:'Oui', no:'Non', photoCount:'{count} photos', status:{ DRAFT:'Brouillon', PENDING_REVIEW:'En attente de révision', APPROVED:'Approuvé', REJECTED:'Rejeté', HIDDEN:'Masqué', SUSPENDED:'Suspendu' }, fields:{ status:'Statut', type:'Type', displayName:'Nom affiché', bio:'Bio', city:'Ville', relationshipStatus:'Statut relationnel', discretion:'Discrétion', gender:'Genre', orientation:'Orientation', country:'Pays', photos:'Photos', verified:'Vérifié', createdAt:'Créé le' } },
    userSubscription:{ title:'Abonnement et informations financières', empty:'Aucun abonnement.', current:'Abonnement actuel', plan:'Formule', status:'Statut', provider:'Fournisseur', startedAt:'Début de l’abonnement', periodStart:'Période actuelle depuis', periodEnd:'Période actuelle jusqu’au', cancelAtEnd:'Annulation en fin de période', cancelledAt:'Annulé le', currentPeriod:'Période actuelle', amountPaid:'Montant payé pendant cette période', lifetime:'Historique total', totalPaid:'Total payé depuis la création du compte', successfulPayments:'Paiements réussis', lastPayment:'Dernier paiement', failedPayments:'Paiements échoués au cours des 90 derniers jours', noLocalHistory:'Les données historiques ne sont pas disponibles localement.', testAccountNote:'Compte de test — ne génère pas d’événements Stripe réels.', yes:'Oui', no:'Non' },
  }},
}
