export const adminOperationsTranslations = {
  'pt-PT': { admin:{
    verifications:{ loadError:'Não foi possível carregar as verificações.', actionError:'Não foi possível concluir a verificação.', activationSuccess:'Verificação aprovada — conta ativada automaticamente.', rejectTitle:'Rejeitar verificação', empty:'Sem verificações pendentes.', noProfile:'Sem perfil', selfieAlt:'Selfie de verificação', noImage:'Sem imagem associada.', approve:'Aprovar', reject:'Rejeitar' },
    conversations:{ loadError:'Não foi possível carregar as conversas.', openError:'Não foi possível abrir a conversa.', reasonRequired:'O motivo é obrigatório para aceder a conversas.', reasonLabel:'Motivo de acesso (obrigatório)', reasonPlaceholder:'Ex.: Investigar denúncia #123', empty:'Sem conversas.', detailTitle:'Detalhe da conversa', back:'Voltar às conversas', auditWarning:'Este acesso foi registado no histórico administrativo.', noMessages:'Sem mensagens.', deletedMessage:'[Eliminada]', messageCount:'{count} mensagens' },
    audit:{ loadError:'Não foi possível carregar a auditoria.', tabs:{ logs:'Log', sessions:'Sessões' }, emptyLogs:'Sem registos administrativos.', emptySessions:'Sem sessões registadas.', by:'Por:', duration:'{minutes} min', active:'● Ativo' },
    beta:{ loadError:'Não foi possível carregar os convites beta.', actionError:'Não foi possível concluir a operação.', createTitle:'Criar convite beta', emailOptional:'Email (opcional)', maxUses:'Número máximo de utilizações', create:'Criar convite', copy:'Copiar', empty:'Sem convites beta.', active:'● Ativo', inactive:'○ Inativo', usage:'{used}/{max} utilizações', activate:'Ativar', deactivate:'Desativar', delete:'Apagar' },
  }},
  en: { admin:{
    verifications:{ loadError:'Verifications could not be loaded.', actionError:'Verification could not be completed.', activationSuccess:'Verification approved — account activated automatically.', rejectTitle:'Reject verification', empty:'No pending verifications.', noProfile:'No profile', selfieAlt:'Verification selfie', noImage:'No image attached.', approve:'Approve', reject:'Reject' },
    conversations:{ loadError:'Conversations could not be loaded.', openError:'The conversation could not be opened.', reasonRequired:'A reason is required to access conversations.', reasonLabel:'Access reason (required)', reasonPlaceholder:'E.g. Investigate report #123', empty:'No conversations.', detailTitle:'Conversation details', back:'Back to conversations', auditWarning:'This access was recorded in the administrative history.', noMessages:'No messages.', deletedMessage:'[Deleted]', messageCount:'{count} messages' },
    audit:{ loadError:'Audit data could not be loaded.', tabs:{ logs:'Log', sessions:'Sessions' }, emptyLogs:'No administrative records.', emptySessions:'No recorded sessions.', by:'By:', duration:'{minutes} min', active:'● Active' },
    beta:{ loadError:'Beta invitations could not be loaded.', actionError:'The operation could not be completed.', createTitle:'Create beta invitation', emailOptional:'Email (optional)', maxUses:'Maximum number of uses', create:'Create invitation', copy:'Copy', empty:'No beta invitations.', active:'● Active', inactive:'○ Inactive', usage:'{used}/{max} uses', activate:'Activate', deactivate:'Deactivate', delete:'Delete' },
  }},
  fr: { admin:{
    verifications:{ loadError:'Les vérifications n’ont pas pu être chargées.', actionError:'La vérification n’a pas pu être effectuée.', activationSuccess:'Vérification approuvée — compte activé automatiquement.', rejectTitle:'Rejeter la vérification', empty:'Aucune vérification en attente.', noProfile:'Sans profil', selfieAlt:'Selfie de vérification', noImage:'Aucune image associée.', approve:'Approuver', reject:'Rejeter' },
    conversations:{ loadError:'Les conversations n’ont pas pu être chargées.', openError:'La conversation n’a pas pu être ouverte.', reasonRequired:'Un motif est obligatoire pour accéder aux conversations.', reasonLabel:'Motif d’accès (obligatoire)', reasonPlaceholder:'Ex. : Examiner le signalement #123', empty:'Aucune conversation.', detailTitle:'Détail de la conversation', back:'Retour aux conversations', auditWarning:'Cet accès a été enregistré dans l’historique administratif.', noMessages:'Aucun message.', deletedMessage:'[Supprimé]', messageCount:'{count} messages' },
    audit:{ loadError:'Les données d’audit n’ont pas pu être chargées.', tabs:{ logs:'Journal', sessions:'Sessions' }, emptyLogs:'Aucun enregistrement administratif.', emptySessions:'Aucune session enregistrée.', by:'Par :', duration:'{minutes} min', active:'● Actif' },
    beta:{ loadError:'Les invitations bêta n’ont pas pu être chargées.', actionError:'L’opération n’a pas pu être effectuée.', createTitle:'Créer une invitation bêta', emailOptional:'E-mail (facultatif)', maxUses:'Nombre maximal d’utilisations', create:'Créer l’invitation', copy:'Copier', empty:'Aucune invitation bêta.', active:'● Actif', inactive:'○ Inactif', usage:'{used}/{max} utilisations', activate:'Activer', deactivate:'Désactiver', delete:'Supprimer' },
  }},
}
