export const adminUserSensitiveTranslations = {
  'pt-PT': { admin: {
    userPrivacy:{ title:'Privacidade', empty:'Sem definições de privacidade disponíveis.', yes:'Sim', no:'Não', readOnly:'Apenas leitura — estas definições são geridas pelo utilizador na aplicação.', fields:{ visibleInDiscovery:'Visível no Discovery', showDistance:'Mostrar distância', showOnlineStatus:'Mostrar estado online', allowPhotoRequests:'Permitir pedidos de fotografias', invisibleMode:'Modo invisível', notificationMode:'Modo de notificações', minDistanceKm:'Distância mínima' } },
    userVerification:{ title:'Verificação', type:'Tipo', statusLabel:'Estado', reviewedAt:'Revisto em', ageVerifiedAt:'Idade verificada em', approve:'Aprovar', reject:'Rejeitar', rejectTitle:'Rejeitar verificação', updated:'Verificação atualizada.', approvedAndActivated:'Verificação aprovada e conta ativada automaticamente.', actionError:'Não foi possível atualizar a verificação.', imageLoading:'A carregar imagem…', imageError:'Não foi possível carregar a imagem; poderá já ter sido eliminada após a revisão.', selfieAlt:'Selfie de verificação', status:{ NONE:'Sem verificação', PENDING:'Pendente', APPROVED:'Aprovada', REJECTED:'Rejeitada' } },
    userHistory:{ title:'Histórico administrativo', restricted:'Histórico visível apenas a administradores.', empty:'Sem histórico.', by:'Por', reason:'Motivo', changes:'Ver alterações', before:'Antes', after:'Depois' },
  }},
  en: { admin: {
    userPrivacy:{ title:'Privacy', empty:'No privacy settings are available.', yes:'Yes', no:'No', readOnly:'Read only — these settings are managed by the user in the application.', fields:{ visibleInDiscovery:'Visible in Discovery', showDistance:'Show distance', showOnlineStatus:'Show online status', allowPhotoRequests:'Allow photo requests', invisibleMode:'Invisible mode', notificationMode:'Notification mode', minDistanceKm:'Minimum distance' } },
    userVerification:{ title:'Verification', type:'Type', statusLabel:'Status', reviewedAt:'Reviewed on', ageVerifiedAt:'Age verified on', approve:'Approve', reject:'Reject', rejectTitle:'Reject verification', updated:'Verification updated.', approvedAndActivated:'Verification approved and account activated automatically.', actionError:'The verification could not be updated.', imageLoading:'Loading image…', imageError:'The image could not be loaded; it may already have been deleted after review.', selfieAlt:'Verification selfie', status:{ NONE:'No verification', PENDING:'Pending', APPROVED:'Approved', REJECTED:'Rejected' } },
    userHistory:{ title:'Administrative history', restricted:'History is visible to administrators only.', empty:'No history.', by:'By', reason:'Reason', changes:'View changes', before:'Before', after:'After' },
  }},
  fr: { admin: {
    userPrivacy:{ title:'Confidentialité', empty:'Aucun paramètre de confidentialité disponible.', yes:'Oui', no:'Non', readOnly:'Lecture seule — ces paramètres sont gérés par l’utilisateur dans l’application.', fields:{ visibleInDiscovery:'Visible dans Discovery', showDistance:'Afficher la distance', showOnlineStatus:'Afficher le statut en ligne', allowPhotoRequests:'Autoriser les demandes de photos', invisibleMode:'Mode invisible', notificationMode:'Mode de notification', minDistanceKm:'Distance minimale' } },
    userVerification:{ title:'Vérification', type:'Type', statusLabel:'Statut', reviewedAt:'Examiné le', ageVerifiedAt:'Âge vérifié le', approve:'Approuver', reject:'Rejeter', rejectTitle:'Rejeter la vérification', updated:'Vérification mise à jour.', approvedAndActivated:'Vérification approuvée et compte activé automatiquement.', actionError:'La vérification n’a pas pu être mise à jour.', imageLoading:'Chargement de l’image…', imageError:'L’image n’a pas pu être chargée ; elle a peut-être déjà été supprimée après l’examen.', selfieAlt:'Selfie de vérification', status:{ NONE:'Aucune vérification', PENDING:'En attente', APPROVED:'Approuvée', REJECTED:'Rejetée' } },
    userHistory:{ title:'Historique administratif', restricted:'L’historique est visible uniquement par les administrateurs.', empty:'Aucun historique.', by:'Par', reason:'Motif', changes:'Voir les modifications', before:'Avant', after:'Après' },
  }},
}
