export const matchesTranslations = {
  'pt-PT': { matches: {
    title:'Os teus Matches', loading:'A carregar...', emptyTitle:'Ainda sem matches', emptyHelp:'Explora perfis e envia pedidos de ligação para criar matches.', activeConnections:'Ligações ativas', tapToChat:'Toca para abrir a Sala Privada', match:'Match', requestsTitle:'Pedidos de ligação', waitingReply:'à espera da tua resposta', wantsConnect:'Quer ligar-se a ti', compatible:'compatível', verified:'verificado', someoneCompatible:'Alguém compatível', years:'anos', reject:'Rejeitar', accept:'Aceitar', premiumProfile:'Ver perfil completo com Between Premium', needsConfirmation:'Pedidos — precisam da tua confirmação', confirmInterest:'Confirmar interesse', sideConfirmed:'do teu lado já confirmaram', confirmHelp:'Confirma o teu interesse para avançar.', waitingEveryone:'À espera de todos', alreadyConfirmed:'Já confirmaste — a aguardar confirmação do outro lado.', requestAcceptError:'Não foi possível aceitar o pedido.', requestRejectError:'Não foi possível rejeitar o pedido.', approvalError:'Não foi possível confirmar o interesse.', roomsError:'Não foi possível abrir a Sala Privada.', unread:'não lida(s)'
  } },
  en: { matches: {
    title:'Your Matches', loading:'Loading...', emptyTitle:'No matches yet', emptyHelp:'Explore profiles and send connection requests to create matches.', activeConnections:'Active connections', tapToChat:'Tap to open the Private Room', match:'Match', requestsTitle:'Connection requests', waitingReply:'waiting for your reply', wantsConnect:'Wants to connect with you', compatible:'compatible', verified:'verified', someoneCompatible:'Someone compatible', years:'years', reject:'Reject', accept:'Accept', premiumProfile:'View full profile with Between Premium', needsConfirmation:'Requests — need your confirmation', confirmInterest:'Confirm interest', sideConfirmed:'on your side have confirmed', confirmHelp:'Confirm your interest to continue.', waitingEveryone:'Waiting for everyone', alreadyConfirmed:'You already confirmed — waiting for the other side.', requestAcceptError:'The request could not be accepted.', requestRejectError:'The request could not be rejected.', approvalError:'The interest could not be confirmed.', roomsError:'The Private Room could not be opened.', unread:'unread'
  } },
  fr: { matches: {
    title:'Vos Matches', loading:'Chargement...', emptyTitle:'Aucun match pour le moment', emptyHelp:'Explorez des profils et envoyez des demandes de connexion pour créer des matches.', activeConnections:'Connexions actives', tapToChat:'Touchez pour ouvrir la Salle Privée', match:'Match', requestsTitle:'Demandes de connexion', waitingReply:'en attente de votre réponse', wantsConnect:'Souhaite se connecter avec vous', compatible:'compatible', verified:'vérifié', someoneCompatible:'Une personne compatible', years:'ans', reject:'Refuser', accept:'Accepter', premiumProfile:'Voir le profil complet avec Between Premium', needsConfirmation:'Demandes — votre confirmation est requise', confirmInterest:'Confirmer l’intérêt', sideConfirmed:'de votre côté ont confirmé', confirmHelp:'Confirmez votre intérêt pour continuer.', waitingEveryone:'En attente de tous', alreadyConfirmed:'Vous avez déjà confirmé — en attente de l’autre partie.', requestAcceptError:'Impossible d’accepter la demande.', requestRejectError:'Impossible de refuser la demande.', approvalError:'Impossible de confirmer l’intérêt.', roomsError:'Impossible d’ouvrir la Salle Privée.', unread:'non lu(s)'
  } }
}
