export const premiumTranslations = {
  'pt-PT': {
    title:'Between Premium', loading:'A carregar…', success:'Subscrição ativada! Bem-vindo/a ao Premium.', cancelled:'Pagamento cancelado. Podes tentar novamente.', testActivated:'Premium ativado em modo de teste.', checkoutError:'Erro ao iniciar o pagamento.', portalError:'Portal de gestão indisponível.', active:'ativo', renews:'Renova em', manage:'Gerir subscrição', processing:'A processar…', subscribe:'Subscrever', month:'/mês', secure:'Pagamento seguro via Stripe.', cancelAnytime:'Podes cancelar a qualquer momento.', discreetBilling:'O nome “Between Us” não aparece no extrato bancário.', coupleRequired:'Cria ou ativa um perfil de casal para aceder ao plano Between Casal.', plans:{ PREMIUM:{ name:'Between Premium', badge:null, features:['Modo Invisível — navega sem seres visto','Travel Mode — explora antes de chegar','Ligar-te a perfis independentemente do Between Score','Ver o perfil completo de quem te enviou um pedido de ligação','Bloqueio de contactos','Soft Reveal avançado','Filtros premium','Verificação de perfil'] }, COUPLE_PREMIUM:{ name:'Between Casal', badge:'Dois perfis, um preço', features:['Tudo do Premium para os dois','Double Consent Match completo','Modo Acordo avançado','Sala Privada partilhada','Vincular dois perfis como casal','Um pagamento cobre ambos os parceiros'] } }
  },
  en: {
    title:'Between Premium', loading:'Loading…', success:'Subscription activated! Welcome to Premium.', cancelled:'Payment cancelled. You can try again.', testActivated:'Premium activated in test mode.', checkoutError:'Unable to start payment.', portalError:'Subscription portal unavailable.', active:'active', renews:'Renews on', manage:'Manage subscription', processing:'Processing…', subscribe:'Subscribe to', month:'/month', secure:'Secure payment via Stripe.', cancelAnytime:'Cancel at any time.', discreetBilling:'“Between Us” does not appear on your bank statement.', coupleRequired:'Create or activate a couple profile to access Between Couple.', plans:{ PREMIUM:{ name:'Between Premium', badge:null, features:['Invisible Mode — browse without being seen','Travel Mode — explore before you arrive','Connect regardless of the Between Score','View the full profile of incoming connection requests','Contact blocking','Advanced Soft Reveal','Premium filters','Profile verification'] }, COUPLE_PREMIUM:{ name:'Between Couple', badge:'Two profiles, one price', features:['Everything in Premium for both people','Full Double Consent Match','Advanced Agreement Mode','Shared Private Room','Link two profiles as a couple','One payment covers both partners'] } }
  },
  fr: {
    title:'Between Premium', loading:'Chargement…', success:'Abonnement activé ! Bienvenue sur Premium.', cancelled:'Paiement annulé. Vous pouvez réessayer.', testActivated:'Premium activé en mode test.', checkoutError:'Impossible de lancer le paiement.', portalError:'Portail de gestion indisponible.', active:'actif', renews:'Renouvellement le', manage:'Gérer l’abonnement', processing:'Traitement…', subscribe:'S’abonner à', month:'/mois', secure:'Paiement sécurisé via Stripe.', cancelAnytime:'Annulation possible à tout moment.', discreetBilling:'Le nom « Between Us » n’apparaît pas sur votre relevé bancaire.', coupleRequired:'Créez ou activez un profil de couple pour accéder à Between Couple.', plans:{ PREMIUM:{ name:'Between Premium', badge:null, features:['Mode invisible — naviguez sans être vu','Travel Mode — explorez avant votre arrivée','Se connecter indépendamment du Between Score','Voir le profil complet des demandes de connexion reçues','Blocage des contacts','Soft Reveal avancé','Filtres premium','Vérification du profil'] }, COUPLE_PREMIUM:{ name:'Between Couple', badge:'Deux profils, un prix', features:['Tout Premium pour les deux personnes','Double Consent Match complet','Mode Accord avancé','Salon privé partagé','Associer deux profils en couple','Un paiement couvre les deux partenaires'] } }
  }
}
