export const profileFormTranslations = {
  'pt-PT': {
    profileForm: {
      title:'Criar o teu perfil', step:'Passo', of:'de', who:'Quem és?', displayName:'Nome visível ou pseudónimo *', bio:'Bio curta (opcional)', gender:'Género (opcional)', orientation:'Orientação (opcional)', homeLocation:'Localização habitual', continue:'Continuar →', back:'← Voltar', lookingFor:'O que procuras?', multiSelect:'Podes selecionar mais do que um.', discretionTitle:'Nível de discrição', discretionHelp:'Controla quem pode ver o teu perfil.', limitsTitle:'Mapa de Limites', limitsHelp:'Opcional — podes definir ou ajustar isto mais tarde no teu perfil. Sim / Talvez / Não para cada tópico.', yes:'Sim', maybe:'Talvez', no:'Não', creating:'A criar...', create:'Criar perfil ✓', displayNameRequired:'O nome visível é obrigatório.', intentionRequired:'Seleciona pelo menos uma intenção.', createError:'Erro ao criar perfil. Tenta novamente.', relationships:{ SINGLE:'Solteiro/a', COMMITTED:'Comprometido/a', MARRIED:'Casado/a', OPEN:'Relação aberta', POLYAMOROUS:'Poliamoroso/a', COUPLE_CURIOUS:'Casal curioso', COUPLE_LIBERAL:'Casal liberal', OTHER:'Outro' }, discretion:{ MAXIMUM:{label:'Máxima privacidade',desc:'Perfil oculto, fotos desfocadas'}, SELECTIVE:{label:'Visibilidade seletiva',desc:'Apareço apenas a perfis compatíveis'}, OPEN:{label:'Perfil aberto',desc:'Visível para todos na plataforma'} }
    }
  },
  en: {
    profileForm: {
      title:'Create your profile', step:'Step', of:'of', who:'Who are you?', displayName:'Display name or pseudonym *', bio:'Short bio (optional)', gender:'Gender (optional)', orientation:'Orientation (optional)', homeLocation:'Home location', continue:'Continue →', back:'← Back', lookingFor:'What are you looking for?', multiSelect:'You can select more than one.', discretionTitle:'Discretion level', discretionHelp:'Control who can see your profile.', limitsTitle:'Boundaries map', limitsHelp:'Optional — you can define or adjust this later in your profile. Yes / Maybe / No for each topic.', yes:'Yes', maybe:'Maybe', no:'No', creating:'Creating...', create:'Create profile ✓', displayNameRequired:'A display name is required.', intentionRequired:'Select at least one intention.', createError:'Unable to create the profile. Please try again.', relationships:{ SINGLE:'Single', COMMITTED:'Committed', MARRIED:'Married', OPEN:'Open relationship', POLYAMOROUS:'Polyamorous', COUPLE_CURIOUS:'Curious couple', COUPLE_LIBERAL:'Lifestyle couple', OTHER:'Other' }, discretion:{ MAXIMUM:{label:'Maximum privacy',desc:'Hidden profile and blurred photos'}, SELECTIVE:{label:'Selective visibility',desc:'Only visible to compatible profiles'}, OPEN:{label:'Open profile',desc:'Visible to everyone on the platform'} }
    }
  },
  fr: {
    profileForm: {
      title:'Créer votre profil', step:'Étape', of:'sur', who:'Qui êtes-vous ?', displayName:'Nom visible ou pseudonyme *', bio:'Courte présentation (facultatif)', gender:'Genre (facultatif)', orientation:'Orientation (facultatif)', homeLocation:'Lieu de résidence', continue:'Continuer →', back:'← Retour', lookingFor:'Que recherchez-vous ?', multiSelect:'Vous pouvez sélectionner plusieurs options.', discretionTitle:'Niveau de discrétion', discretionHelp:'Contrôlez qui peut voir votre profil.', limitsTitle:'Carte des limites', limitsHelp:'Facultatif — vous pourrez définir ou modifier ces choix plus tard. Oui / Peut-être / Non pour chaque sujet.', yes:'Oui', maybe:'Peut-être', no:'Non', creating:'Création...', create:'Créer le profil ✓', displayNameRequired:'Un nom visible est obligatoire.', intentionRequired:'Sélectionnez au moins une intention.', createError:'Impossible de créer le profil. Réessayez.', relationships:{ SINGLE:'Célibataire', COMMITTED:'En couple', MARRIED:'Marié(e)', OPEN:'Relation ouverte', POLYAMOROUS:'Polyamoureux/se', COUPLE_CURIOUS:'Couple curieux', COUPLE_LIBERAL:'Couple libertin', OTHER:'Autre' }, discretion:{ MAXIMUM:{label:'Confidentialité maximale',desc:'Profil masqué et photos floutées'}, SELECTIVE:{label:'Visibilité sélective',desc:'Visible uniquement par les profils compatibles'}, OPEN:{label:'Profil ouvert',desc:'Visible par tous sur la plateforme'} }
    }
  }
}
