export const profileFormTranslations = {
  'pt-PT': {
    profileForm: {
      title:'Criar o teu perfil', step:'Passo', of:'de', who:'Quem és?', displayName:'Nome visível ou pseudónimo *', bio:'Bio curta (opcional)', gender:'Género (opcional)', orientation:'Orientação (opcional)', homeLocation:'Localização habitual', continue:'Continuar →', back:'← Voltar', lookingFor:'O que procuras?', multiSelect:'Podes selecionar mais do que um.', discretionTitle:'Nível de discrição', discretionHelp:'Controla quem pode ver o teu perfil.', limitsTitle:'Mapa de Limites', limitsHelp:'Opcional — podes definir ou ajustar isto mais tarde no teu perfil. Sim / Talvez / Não para cada tópico.', yes:'Sim', maybe:'Talvez', no:'Não', creating:'A criar...', create:'Criar perfil ✓', displayNameRequired:'O nome visível é obrigatório.', intentionRequired:'Seleciona pelo menos uma intenção.', createError:'Erro ao criar perfil. Tenta novamente.', relationships:{ SINGLE:'Solteiro/a', COMMITTED:'Comprometido/a', MARRIED:'Casado/a', OPEN:'Relação aberta', POLYAMOROUS:'Poliamoroso/a', COUPLE_CURIOUS:'Casal curioso', COUPLE_LIBERAL:'Casal liberal', OTHER:'Outro' }, discretion:{ MAXIMUM:{label:'Máxima privacidade',desc:'Perfil oculto, fotos desfocadas'}, SELECTIVE:{label:'Visibilidade seletiva',desc:'Apareço apenas a perfis compatíveis'}, OPEN:{label:'Perfil aberto',desc:'Visível para todos na plataforma'} }
    },
    editProfile: {
      title:'Editar perfil', save:'Guardar', saving:'A guardar…', saveChanges:'Guardar alterações', updated:'Perfil atualizado!', saveError:'Erro ao guardar.', loading:'A carregar…', displayNameRequired:'O nome visível é obrigatório.',
      completeness:'Perfil', complete:'completo', missing:'Falta', basicData:'Dados do perfil', displayName:'Nome visível *', displayNamePlaceholder:'Nome ou pseudónimo', bio:'Bio', bioPlaceholder:'Breve descrição (opcional)', homeLocation:'Localização habitual', locationDisplay:'Mostrar no perfil como',
      locationOptions:{ REFERENCE_LOCALITY:'Nome da localidade (ex.: Benedita)', CUSTOM_LOCALITY:'Localidade específica, se preenchida (ex.: bairro)', REGION_ONLY:'Apenas distrito/região (ex.: Distrito de Leiria)' },
      locationHelp:'Depois de confirmada, só podes voltar a mudar a localização habitual passado algum tempo. Para viajar temporariamente, utiliza o Travel Mode.', gender:'Género', orientation:'Orientação', preferNotSay:'Prefiro não dizer / não definido', relationship:'Estado relacional', intentions:'O que procuras', limits:'Mapa de Limites', limitsHelp:'Sim / Talvez / Não para cada tópico.', discretion:'Nível de discrição', yes:'Sim', maybe:'Talvez', no:'Não',
      missingFields:{ DISPLAY_NAME:'nome visível', MEMBERS:'convidar parceiro ou membros', GENDER:'género', INTENTIONS:'o que procuras', BOUNDARIES:'mapa de limites', PRIMARY_PHOTO:'fotografia de perfil', PRIVACY_SETTINGS:'definições de privacidade', BIO:'biografia' }
    }
  },
  en: {
    profileForm: {
      title:'Create your profile', step:'Step', of:'of', who:'Who are you?', displayName:'Display name or pseudonym *', bio:'Short bio (optional)', gender:'Gender (optional)', orientation:'Orientation (optional)', homeLocation:'Home location', continue:'Continue →', back:'← Back', lookingFor:'What are you looking for?', multiSelect:'You can select more than one.', discretionTitle:'Discretion level', discretionHelp:'Control who can see your profile.', limitsTitle:'Boundaries map', limitsHelp:'Optional — you can define or adjust this later in your profile. Yes / Maybe / No for each topic.', yes:'Yes', maybe:'Maybe', no:'No', creating:'Creating...', create:'Create profile ✓', displayNameRequired:'A display name is required.', intentionRequired:'Select at least one intention.', createError:'Unable to create the profile. Please try again.', relationships:{ SINGLE:'Single', COMMITTED:'Committed', MARRIED:'Married', OPEN:'Open relationship', POLYAMOROUS:'Polyamorous', COUPLE_CURIOUS:'Curious couple', COUPLE_LIBERAL:'Lifestyle couple', OTHER:'Other' }, discretion:{ MAXIMUM:{label:'Maximum privacy',desc:'Hidden profile and blurred photos'}, SELECTIVE:{label:'Selective visibility',desc:'Only visible to compatible profiles'}, OPEN:{label:'Open profile',desc:'Visible to everyone on the platform'} }
    },
    editProfile: {
      title:'Edit profile', save:'Save', saving:'Saving…', saveChanges:'Save changes', updated:'Profile updated!', saveError:'Unable to save.', loading:'Loading…', displayNameRequired:'A display name is required.',
      completeness:'Profile', complete:'complete', missing:'Missing', basicData:'Profile details', displayName:'Display name *', displayNamePlaceholder:'Name or pseudonym', bio:'Bio', bioPlaceholder:'Short description (optional)', homeLocation:'Home location', locationDisplay:'Show on profile as',
      locationOptions:{ REFERENCE_LOCALITY:'Locality name (e.g. Benedita)', CUSTOM_LOCALITY:'Specific locality, when provided (e.g. neighbourhood)', REGION_ONLY:'District or region only (e.g. Leiria District)' },
      locationHelp:'Once confirmed, your home location can only be changed again after a waiting period. Use Travel Mode for temporary trips.', gender:'Gender', orientation:'Orientation', preferNotSay:'Prefer not to say / not set', relationship:'Relationship status', intentions:'What you are looking for', limits:'Boundaries map', limitsHelp:'Yes / Maybe / No for each topic.', discretion:'Discretion level', yes:'Yes', maybe:'Maybe', no:'No',
      missingFields:{ DISPLAY_NAME:'display name', MEMBERS:'invite a partner or members', GENDER:'gender', INTENTIONS:'what you are looking for', BOUNDARIES:'boundaries map', PRIMARY_PHOTO:'profile photo', PRIVACY_SETTINGS:'privacy settings', BIO:'bio' }
    }
  },
  fr: {
    profileForm: {
      title:'Créer votre profil', step:'Étape', of:'sur', who:'Qui êtes-vous ?', displayName:'Nom visible ou pseudonyme *', bio:'Courte présentation (facultatif)', gender:'Genre (facultatif)', orientation:'Orientation (facultatif)', homeLocation:'Lieu de résidence', continue:'Continuer →', back:'← Retour', lookingFor:'Que recherchez-vous ?', multiSelect:'Vous pouvez sélectionner plusieurs options.', discretionTitle:'Niveau de discrétion', discretionHelp:'Contrôlez qui peut voir votre profil.', limitsTitle:'Carte des limites', limitsHelp:'Facultatif — vous pourrez définir ou modifier ces choix plus tard. Oui / Peut-être / Non pour chaque sujet.', yes:'Oui', maybe:'Peut-être', no:'Non', creating:'Création...', create:'Créer le profil ✓', displayNameRequired:'Un nom visible est obligatoire.', intentionRequired:'Sélectionnez au moins une intention.', createError:'Impossible de créer le profil. Réessayez.', relationships:{ SINGLE:'Célibataire', COMMITTED:'En couple', MARRIED:'Marié(e)', OPEN:'Relation ouverte', POLYAMOROUS:'Polyamoureux/se', COUPLE_CURIOUS:'Couple curieux', COUPLE_LIBERAL:'Couple libertin', OTHER:'Autre' }, discretion:{ MAXIMUM:{label:'Confidentialité maximale',desc:'Profil masqué et photos floutées'}, SELECTIVE:{label:'Visibilité sélective',desc:'Visible uniquement par les profils compatibles'}, OPEN:{label:'Profil ouvert',desc:'Visible par tous sur la plateforme'} }
    },
    editProfile: {
      title:'Modifier le profil', save:'Enregistrer', saving:'Enregistrement…', saveChanges:'Enregistrer les modifications', updated:'Profil mis à jour !', saveError:'Impossible d’enregistrer.', loading:'Chargement…', displayNameRequired:'Un nom visible est obligatoire.',
      completeness:'Profil', complete:'complet', missing:'Manque', basicData:'Informations du profil', displayName:'Nom visible *', displayNamePlaceholder:'Nom ou pseudonyme', bio:'Présentation', bioPlaceholder:'Courte description (facultatif)', homeLocation:'Lieu de résidence', locationDisplay:'Afficher sur le profil comme',
      locationOptions:{ REFERENCE_LOCALITY:'Nom de la localité (ex. : Benedita)', CUSTOM_LOCALITY:'Localité précise si renseignée (ex. : quartier)', REGION_ONLY:'District ou région uniquement (ex. : district de Leiria)' },
      locationHelp:'Une fois confirmé, le lieu de résidence ne peut être modifié qu’après un délai. Utilisez le mode Voyage pour les déplacements temporaires.', gender:'Genre', orientation:'Orientation', preferNotSay:'Préfère ne pas répondre / non défini', relationship:'Situation relationnelle', intentions:'Ce que vous recherchez', limits:'Carte des limites', limitsHelp:'Oui / Peut-être / Non pour chaque sujet.', discretion:'Niveau de discrétion', yes:'Oui', maybe:'Peut-être', no:'Non',
      missingFields:{ DISPLAY_NAME:'nom visible', MEMBERS:'inviter un partenaire ou des membres', GENDER:'genre', INTENTIONS:'ce que vous recherchez', BOUNDARIES:'carte des limites', PRIMARY_PHOTO:'photo de profil', PRIVACY_SETTINGS:'paramètres de confidentialité', BIO:'présentation' }
    }
  }
}
